### ISSUE TITLE
Bug in Form tests after added "prop-types"

### ISSUE THREAD

**Issue by vbandelier** [testdrivenio/testdriven-app-2.3#20]
Just after added the package prop-types I had the following error in Form tests:

FAIL  src/components/__tests__/Form.test.jsx
  ● When not authenticated › Register Form submits the form properly

    expect(jest.fn()).toHaveBeenCalledTimes(1)
    
    Expected mock function to have been called one time, but it was called three times.
      
      at Object.it (src/components/__tests__/Form.test.jsx:58:47)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ● When not authenticated › Login Form submits the form properly

    expect(jest.fn()).toHaveBeenCalledTimes(1)
    
    Expected mock function to have been called one time, but it was called three times.
      
      at Object.it (src/components/__tests__/Form.test.jsx:58:47)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

Has anyone had the same problem and can help me?

**Comment by mjhea0** [comment]
is this still an issue?
