### ISSUE TITLE
Cypress setup not working

### ISSUE THREAD

**Issue by caseyrieder** [testdrivenio/testdriven-app-2.3#22]
I wired up Cypress to work with the initial test. However, I am trying to run it through the full suite within `test.sh`, and I keep getting the following error:

```
>   Running: index.test.js...                                                                (1 of 1)
> 
> 
>   Index
>     1) users should be able to view the index page
> 
> 
>   0 passing (312ms)
>   1 failing
> 
>   1) Index users should be able to view the index page:
>      CypressError: cy.visit() failed trying to load:
> 
> http://localhost/
> 
> We attempted to make an http request to this URL but the request failed without a response.
> 
> We received this error at the network level:
> 
>   > Error: connect ECONNREFUSED 127.0.0.1:80
> 
> Common situations why this would fail:
>   - you don't have internet access
>   - you forgot to run / boot your web server
>   - your web server isn't accessible
>   - you have weird network configuration settings on your computer
> 
> The stack trace for this error is:
> 
> Error: connect ECONNREFUSED 127.0.0.1:80
>     at Object.exports._errnoException (util.js:1024:11)
>     at exports._exceptionWithHostPort (util.js:1047:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
> 
>       at Object.cypressErr (http://localhost:62040/__cypress/runner/cypress_runner.js:67483:11)
>       at Object.throwErr (http://localhost:62040/__cypress/runner/cypress_runner.js:67448:18)
>       at Object.throwErrByPath (http://localhost:62040/__cypress/runner/cypress_runner.js:67475:17)
>       at http://localhost:62040/__cypress/runner/cypress_runner.js:58333:31
>       at visitFailedByErr (http://localhost:62040/__cypress/runner/cypress_runner.js:57944:12)
>       at http://localhost:62040/__cypress/runner/cypress_runner.js:58332:22
>       at tryCatcher (http://localhost:62040/__cypress/runner/cypress_runner.js:6846:23)
>       at Promise._settlePromiseFromHandler (http://localhost:62040/__cypress/runner/cypress_runner.js:4868:31)
>       at Promise._settlePromise (http://localhost:62040/__cypress/runner/cypress_runner.js:4925:18)
>       at Promise._settlePromise0 (http://localhost:62040/__cypress/runner/cypress_runner.js:4970:10)
>       at Promise._settlePromises (http://localhost:62040/__cypress/runner/cypress_runner.js:5045:18)
>       at Async._drainQueue (http://localhost:62040/__cypress/runner/cypress_runner.js:1778:16)
>       at Async._drainQueues (http://localhost:62040/__cypress/runner/cypress_runner.js:1788:10)
>       at Async.drainQueues (http://localhost:62040/__cypress/runner/cypress_runner.js:1662:14)
>       at <anonymous>
```

I've rolled things back to the basic dev environment, using the commands that you outline at the beginning of Part 4. Now, all of my tests are passing and the page is mostly rendering at http://localhost. **However**, the API call to get users is returning the following error: `GET http://localhost/users 500 (INTERNAL SERVER ERROR)` in Chrome DevTools. I have no idea what I've done wrong, and I have even resorted to essentially copy-pasting the code from your repo. I guess there is a problem with some part of my setup but I can;t figure it out.

Can anyone help?
Thanks in advance

**Comment by mjhea0** [comment]
Can you shoot me an email at michael at mherman dot org. Thanks!
